version: '2'

services:
  opengrok:
    image: itszero/opengrok
    volumes:
      - source:/src:ro
    environment:
      VIRTUAL_HOST: php-lxr.adamharvey.name,lxr.php.net
      VIRTUAL_PORT: 8080

  updater:
    build: updater
    volumes:
      - ./updater/tasks:/etc/periodic:ro
      - source:/src

volumes:
  source:
    driver: local
