opengrok:
  image: itszero/opengrok
  volumes:
    - source:/src:ro
  environment:
    VIRTUAL_HOST: php-lxr.adamharvey.name,lxr.php.net
    VIRTUAL_PORT: 8080
    LETSENCRYPT_HOST: php-lxr.adamharvey.name
    LETSENCRYPT_EMAIL: aharvey@php.net

updater:
  build: updater
  volumes:
    - ./updater/tasks:/etc/periodic:ro
    - source:/src
