#!/bin/sh

set -e
set -x

cd /src
git clone https://github.com/php/php-src.git master
git-new-workdir master PHP-5.2 PHP-5.2
git-new-workdir master PHP-5.3 PHP-5.3
git-new-workdir master PHP-5.4 PHP-5.4
git-new-workdir master PHP-5.5 PHP-5.5
git-new-workdir master PHP-5.6 PHP-5.6
git-new-workdir master PHP-7.0 PHP-7.0
git-new-workdir master PHP-7.1 PHP-7.1
